name: doc_scan_example
description: "Demonstrates how to use the doc_scan plugin."
publish_to: 'none'

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter

  doc_scan_flutter:
    path: ../

dev_dependencies:
  very_good_analysis: ^10.2.0

flutter:
  uses-material-design: true
