name: doc_scan
description: "A Flutter plugin for scanning documents with automatic edge detection, cropping, and enhancement. Uses ML Kit on Android and VisionKit on iOS for high-quality scans in PDF or JPEG format."
version: 1.0.1
homepage: https://github.com/martin-ideeri/doc_scan
repository: https://github.com/martin-ideeri/doc_scan
issue_tracker: https://github.com/martin-ideeri/doc_scan/issues

topics:
  - document-scanner
  - pdf-scanner
  - flutter-plugin
  - visionkit
  - mlkit

environment:
  sdk: ^3.7.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  very_good_analysis: ^7.0.0

flutter:
  plugin:
    platforms:
      android:
        package: fr.ideeri.doc_scan
        pluginClass: DocScanPlugin
      ios:
        pluginClass: DocScanPlugin
